### ISSUE TITLE
Only one DML wrapper command

### ISSUE THREAD

**Issue by deingithub** [The-Valley-Discord/blimp#6]
No more incomprehensible, long ass, `ticket! updatecategory` with seven arguments, but something like `configure! <toml>`, where `<toml>` e.g. is
```toml
[tickets.category.784671579655319552]
transcript_channel = 327076567072407552
```
and automagically compute a diff to apply to the database. 
Add more wizard commands to make that bearable.
